### ISSUE TITLE
MyCycle 

### ISSUE THREAD

**Issue by munderseth** [s2testorg/testBoard#7]
MyCycle Issue. 
 ```
  testspace:
    branch: simple.cycles
    specs: 
      path: cycle
 ```
